EqAspNet4Demo/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using X.PagedList;

using Korzh.EasyQuery.Linq;

using EqDemo.Models;

namespace EqDemo.Controllers
{
    [RoutePrefix("fulltext-search")]
    public class CustomerController: Controller
    {

        private readonly ApplicationDbContext _dbContext;

        public CustomerController()
        {
            _dbContext = new ApplicationDbContext();
        }


        [Route("")]
        public ActionResult Index(string text, int? page)
        {
            var result = (!string.IsNullOrEmpty(text))
                        ? _dbContext.Customers.FullTextSearchQuery(text)
                        : _dbContext.Customers;

            if (!page.HasValue)
                page = 1;

            var pageNumber = page ?? 1;
    
            ViewBag.PageOfCustomers = result.OrderBy(c => c.Id).ToPagedList(pageNumber, 25);
            ViewBag.Text = text;

            return View("Customers");
        }
    }
}

EqAspNet4Demo/Controllers/EasyQuery/AdvancedSearchController.cs
using System;
using System.Configuration;
using System.Web.Http;
using System.Data.SqlClient;

using Korzh.EasyQuery.Services;
using Korzh.EasyQuery.AspNet;

namespace EqDemo.Controllers
{
    [RoutePrefix("api/easyquery")]
    public class AdvancedSearchController : EasyQueryApiController
    {
        protected override void ConfigureEasyQueryOptions(EasyQueryOptions options)
        {
            options.UseManager<EasyQueryManagerSql>();
            options.DefaultModelId = "NWindSQL";
            options.BuildQueryOnSync = true;

            ConnectionStringSettings connectionSettings = ConfigurationManager.ConnectionStrings["DefaultConnection"];
            if (connectionSettings == null || string.IsNullOrEmpty(connectionSettings.ConnectionString)) {
                throw new Exception("Fatal error: missing connecting string in web.config file");
            }

            options.UseDbConnection<SqlConnection>(connectionSettings.ConnectionString);

            var path = System.Web.Hosting.HostingEnvironment.MapPath("~/App_Data");
            options.UseModelLoader((_) => new FileModelLoader(path));
            options.UseQueryStore((_) => new FileQueryStore(path));

            // Uncomment this line if you want to load model directly from connection 
            // Do not forget to uncomment SqlClientGate registration in WebApiConfig.cs file
            //options.UseDbConnectionModelLoader(config => {
            //    // Ignores Asp.Net Identity tables
            //    config.AddTableFilter((table) => !table.Name.StartsWith("Asp") 
            //                                  && table.Name != "IdentityUsers"
            //                                  && table.Name != "__MigrationHistory");

            //    // Ignores Reports table
            //    config.AddTableFilter((table) => table.Name != "Reports");
            //});
        }
    }
}

EqAspNet4Demo/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

using Korzh.EasyQuery.Services;
using Korzh.EasyQuery.Linq;
using Korzh.EasyQuery.AspNet;

using EqDemo.Models;

namespace EqDemo.Controllers
{
    [RoutePrefix("data-filtering")]
    public class OrderController : Controller
    {
        EasyQueryManagerLinq<Order> _eqManager;
        ApplicationDbContext _dbContext;

        public OrderController()
        {
            _dbContext = ApplicationDbContext.Create();
            var services = new EmptyServiceProvider();

            var options = new EasyQueryOptions(services);
            options.UseEntity(_ => _dbContext.Orders);

            //create EasyQuery manager which generates LINQ queries
            _eqManager = new EasyQueryManagerLinq<Order>(options);
        }

        // GET
        [Route]
        public ActionResult Index()
        {
            return View("Orders");
        }

        /// <summary>
        /// Gets the model by its ID
        /// </summary>
        /// <param name="modelId">The ID of the model that will be loaded</param>
        /// <returns><see cref="ActionResult"/> An ActionResult object with JSON representation of the model</returns>
        [HttpGet]
        [Route("models/{modelId}")]
        public async Task<ActionResult> GetModelAsync(string modelId)
        {
            var model = await _eqManager.GetModelAsync(modelId);
            return this.EqOk(new { model }); 
        }

        /// <summary>
        /// This action returns a list values for specified value editor.
        /// </summary>
        /// <param name="modelId">The ID of the model the value editor belongs to.</param>
        /// <param name="modelId">The ID of the value editor. It can be any LIST value editor (SQL LIST, CONST LIST, etc).</param>
        /// <returns>A <see cref="ActionResult"/> object with a JSON represantation of the list.</returns>
        [HttpGet]
        [Route("models/{modelId}/valuelists/{editorId}")]
        public async Task<ActionResult> GetList(string modelId, string editorId)
        {
            var list = await _eqManager.GetValueListAsync(modelId, editorId);

            return this.EqOk(new { values = list });
        }

        /// <summary>
        /// This action is called when user clicks on "Apply" button in FilterBar or other data-filtering widget
        /// </summary>
        /// <returns>An ActionResult object that contains a partial view with the filtered result set.</returns>
        [HttpPost]
        [Route("models/{modelId}/fetch")]
        public async Task<ActionResult> ApplyQueryFilter(string modelId, string queryId)
        {
            Request.InputStream.Position = 0;
 
            await _eqManager.ReadRequestContentFromStreamAsync(modelId, Request.InputStream);
            var query = _eqManager.Query;

            var queryable = _dbContext.Orders
                .Include(o => o.Customer)
                .Include(o => o.Employee)
                .OrderBy(o => o.Id)
                .DynamicQuery<Order>(query);

            var list = queryable.ToPagedList(_eqManager.Chunk.Page, 15);

            return View("_OrderListPartial", list);
        }
    }
}

EqAspNet4Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@(ViewData["IsIndexPage"] == null ? @ViewData["Title"] + " - " : "")EasyQuery library samples</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
          crossorigin="anonymous"
          integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />

    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/themes/flick/jquery-ui.css">

    <link rel="stylesheet" href="~/Content/root.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />

    @RenderSection("Styles", required: false)

</head>
<body>

    <header class="navbar border-bottom mb-3 p-0 container-fluid px-5">
        <div class="header my-2">
            <a href="~/"><div class="logo-title">EasyQuery Demo</div></a>
            <!--<div class="sub-title">User-friendly ad-hoc query builder for your web-site</div>-->
        </div>
        @Html.Partial("_LoginPartial")
        <div class="nav-item dropdown project-dropdown">
            <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @ViewData["MenuTitle"]
            </a>
            <div class="dropdown-menu dropdown-menu-right project-menu" aria-labelledby="bd-versions">
                @Html.ActionLink("Menu", "Index", "Home", null, new { @class = "dropdown-item" })
                <div class="dropdown-divider"></div>
                @Html.ActionLink("Advanced Search demo", "AdvancedSearch", "Home", null, new { @class = "dropdown-item" })
                <div class="dropdown-divider"></div>
                @Html.ActionLink("Ad-hoc reporting demo", "AdHocReporting", "Home", null, new { @class = "dropdown-item" })
                <div class="dropdown-divider"></div>
                @Html.ActionLink("Data Filtering demo", "Index", "Order", null, new { @class = "dropdown-item" })
                <div class="dropdown-divider"></div>
                @Html.ActionLink("Full-text Search demo", "Index", "Customer", null, new { @class = "dropdown-item" })
            </div>
        </div>
    </header>
    <div class="global-message"></div>

    @RenderBody()

    <footer class="footer container-fluid px-5">
        <div class="float-right">Powered by <a href="https://korzh.com/easyquery">EasyQuery</a></div>
        <div>Copyright 2019 © <a href="https://korzh.com">Korzh.com</a></div>
    </footer>

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/jquery-ui.min.js" type="text/javascript"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" type="text/javascript"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>